export const dynamic = "force-dynamic";
export const revalidate = 0;
import { createClient } from "@/lib/supabase/server";
import { getAppContext } from "@/lib/context/server-context";
import { ContextSelector } from "@/components/layout/context-selector";
import { annualSummary, costPerKg, monthlyFinancialSeries, operationCostBreakdown, tonPerHa } from "@/lib/calculations/annual";
import { formatCompactRupiah, formatNumber, formatRupiah } from "@/lib/formatters";
const MONTHS=["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des"];
export default async function AnalyticsPage(){
 const supabase=await createClient(); const context=await getAppContext();
 const [er,br,hr,or]=await Promise.all([supabase.from("estates").select("*").order("created_at"),supabase.from("blocks").select("*").order("name"),supabase.from("harvests").select("*"),supabase.from("operations").select("*")]);
 for(const r of [er,br,hr,or]) if(r.error) throw new Error(r.error.message);
 const estates=er.data??[],blocks=br.data??[],harvests=hr.data??[],operations=or.data??[]; const estate=estates.find(e=>e.id===context.activeEstateId)??estates[0]??null;
 if(!estate)return <section className="emptyState"><h1>Belum ada kebun</h1><p>Analytics membutuhkan minimal satu kebun.</p></section>;
 const eb=blocks.filter(b=>b.estate_id===estate.id),area=eb.reduce((s,b)=>s+Number(b.area??0),0),summary=annualSummary(harvests,operations,estate.id,context.selectedYear),monthly=monthlyFinancialSeries(harvests,operations,estate.id,context.selectedYear),costs=operationCostBreakdown(operations,estate.id,context.selectedYear);
 const productivity=tonPerHa(summary.productionKg,area),unitCost=costPerKg(summary.productionKg,summary.cost),marginPct=summary.revenue>0?summary.margin/summary.revenue*100:0,maxProduction=Math.max(...monthly.map(m=>m.productionKg),1),maxFinance=Math.max(...monthly.flatMap(m=>[m.revenue,m.cost]),1);
 const rows=eb.map(b=>{const s=annualSummary(harvests.filter(h=>h.block_id===b.id),operations.filter(o=>o.block_id===b.id),estate.id,context.selectedYear),a=Number(b.area??0);return{id:b.id,name:b.name,area:a,...s,productivity:tonPerHa(s.productionKg,a),costKg:costPerKg(s.productionKg,s.cost)}}),ranked=[...rows].sort((a,b)=>b.productivity-a.productivity),best=ranked.find(r=>r.productionKg>0)??null,costly=[...rows].filter(r=>r.productionKg>0).sort((a,b)=>b.costKg-a.costKg)[0]??null,peak=[...monthly].sort((a,b)=>b.productionKg-a.productionKg)[0];
 return <div className="analyticsPage">
 <section className="analyticsHeading"><div><span>OWNER ANALYTICS</span><h1>Analytics Kebun</h1><p>Analisis kinerja memakai calculation engine yang sama dengan Laporan. Periode mengikuti Kebun Aktif dan Tahun Global.</p></div><ContextSelector estates={estates.map(e=>({id:e.id,name:e.name}))} selectedYear={context.selectedYear} activeEstateId={estate.id}/></section>
 <section className="analyticsHero"><div><span>PERFORMANCE VIEW</span><h2>{estate.name}</h2><p>{context.selectedYear} · {eb.length} blok · {formatNumber(area)} Ha</p></div><div className="analyticsHeroMetric"><small>MARGIN</small><strong>{marginPct.toLocaleString("id-ID",{maximumFractionDigits:1})}%</strong><span>{summary.margin>=0?"Kinerja positif":"Perlu perhatian"}</span></div></section>
 <section className="analyticsKpis"><article><small>Produktivitas</small><strong>{productivity.toLocaleString("id-ID",{maximumFractionDigits:2})} t/Ha</strong><span>{formatNumber(summary.productionKg)} Kg produksi</span></article><article><small>Biaya / Kg</small><strong>{formatRupiah(unitCost)}</strong><span>{formatCompactRupiah(summary.cost)} biaya aktual</span></article><article><small>Blok Terproduktif</small><strong>{best?.name??"—"}</strong><span>{best?`${best.productivity.toLocaleString("id-ID",{maximumFractionDigits:2})} t/Ha`:"Belum ada produksi"}</span></article><article><small>Puncak Produksi</small><strong>{peak.productionKg>0?MONTHS[peak.month-1]:"—"}</strong><span>{formatNumber(peak.productionKg)} Kg</span></article></section>
 <section className="analyticsGrid"><article className="analyticsPanel"><header><div><span>TREN PRODUKSI</span><h2>Produksi Bulanan</h2></div><b>{context.selectedYear}</b></header><div className="productionChart">{monthly.map((m,i)=><div className="productionMonth" key={m.month}><div className="productionTrack"><i style={{height:`${Math.max(m.productionKg?4:0,m.productionKg/maxProduction*100)}%`}}/></div><small>{MONTHS[i]}</small></div>)}</div></article><article className="analyticsPanel analyticsInsight"><header><div><span>OWNER INSIGHT</span><h2>Snapshot Kinerja</h2></div></header><div className="insightList"><div><span>Margin Tahun</span><strong>{formatCompactRupiah(summary.margin)}</strong><small>{marginPct.toLocaleString("id-ID",{maximumFractionDigits:1})}% dari pendapatan</small></div><div><span>Efisiensi Biaya</span><strong>{formatRupiah(unitCost)}/Kg</strong><small>Biaya aktual ÷ produksi aktual</small></div><div><span>Blok Biaya/Kg Tertinggi</span><strong>{costly?.name??"—"}</strong><small>{costly?`${formatRupiah(costly.costKg)}/Kg`:"Belum dapat dihitung"}</small></div></div></article></section>
 <section className="analyticsGrid analyticsSecondGrid"><article className="analyticsPanel"><header><div><span>FINANSIAL</span><h2>Pendapatan vs Biaya</h2></div></header><div className="analyticsFinanceChart">{monthly.map((m,i)=><div className="analyticsFinanceMonth" key={m.month}><div><i className="analyticsRevenue" style={{height:`${Math.max(m.revenue?4:0,m.revenue/maxFinance*100)}%`}}/><i className="analyticsCost" style={{height:`${Math.max(m.cost?4:0,m.cost/maxFinance*100)}%`}}/></div><small>{MONTHS[i]}</small></div>)}</div><div className="chartLegend"><span><i className="legendRevenue"/>Pendapatan</span><span><i className="legendCost"/>Biaya</span></div></article><article className="analyticsPanel"><header><div><span>KOMPOSISI BIAYA</span><h2>Cost Driver</h2></div><b>{costs.length} kategori</b></header><div className="analyticsCosts">{costs.length?costs.map(c=>{const pct=summary.cost>0?c.cost/summary.cost*100:0;return <div key={c.type}><div><b>{c.type}</b><strong>{formatCompactRupiah(c.cost)}</strong></div><span><i style={{width:`${Math.min(100,pct)}%`}}/></span><small>{pct.toLocaleString("id-ID",{maximumFractionDigits:1})}%</small></div>}):<div className="emptyRecent">Belum ada biaya aktual.</div>}</div></article></section>
 <section className="analyticsPanel"><header><div><span>RANKING BLOK</span><h2>Produktivitas & Efisiensi</h2></div><b>{rows.length} blok</b></header><div className="monthlyTableWrap"><table className="reportTable analyticsTable"><thead><tr><th>Rank</th><th>Blok</th><th>Luas</th><th>Produksi</th><th>t/Ha</th><th>Pendapatan</th><th>Biaya</th><th>Biaya/Kg</th><th>Margin</th></tr></thead><tbody>{ranked.map((r,i)=><tr key={r.id}><td>#{i+1}</td><td><b>{r.name}</b></td><td>{formatNumber(r.area)} Ha</td><td>{formatNumber(r.productionKg,0)} Kg</td><td className="positiveValue">{r.productivity.toLocaleString("id-ID",{maximumFractionDigits:2})}</td><td>{formatCompactRupiah(r.revenue)}</td><td>{formatCompactRupiah(r.cost)}</td><td>{r.productionKg>0?formatRupiah(r.costKg):"—"}</td><td className={r.margin<0?"negativeValue":"positiveValue"}>{formatCompactRupiah(r.margin)}</td></tr>)}</tbody></table></div></section>
 <div className="reportFootnote">Analytics bersifat read-only. Semua angka aktual berasal dari harvests dan operations pada Tahun Global terpilih; PLAN belum dihitung sebagai Actual sampai direalisasikan.</div></div>;
}
